 FROM alpine

RUN apk update && apk upgrade
RUN apk add nginx

EXPOSE 80 443
#COPY ./www/index.php /usr/share/nginx/html/index.php
#COPY ./hosts/default.conf /etc/nginx/http.d/default.conf
CMD ["nginx","-g","daemon off;"]